// HACKING.adoc for QFeeds
:toc:

= Hacking guide for contributors =

== About ==

This file contains notes to explain how to start debugging or
developing of QFeeds.

== Prepare ==

* Run `make libs`

* Run `make all`

* This produces 2 local folders: `firefox-qfeeds` and `chrome-qfeeds`

== Chrome ==

* Start Google Chrome browser

* Invoke _Menu_ | _Tools_ | _Extensions_ (or enter URL: `chrome://extensions`)

* From page Extensions enable _Developer mode_

* Click _Load unpacked extension_

* Navigate to the directory `chrome-qfeeds`,
  select the directory by name (contents of the extension is inside it)

* The icon of QFeeds should appear in the areas for extensions

== Firefox ==

There are two ways to work on extensions in Firefox.

The *quick way* is to load the extension temporarely for the duration
of the current session. This has to be repeated every time Firefox is
started, all data from the previous session is *lost*.

A *persistent installation* is better suited for the development work
of _QFeeds_. The steps for that are:

* *Download* Firefox Developer Edition:
   https://www.mozilla.org/en-US/firefox/developer/

* *Untar* into a local folder
+
....
mkdir -p ~/.local/bin
cd ~/.local/bin
tar -xvf ~/Downloads/firefox-60.0b3.tar.bz2
....

* Start from that folder, this will also *create the profile upon
first start*
+
....
cd ~/.local/bin/firefox
./firefox
....

* *Enable usigned* extensions
+
. Enter URL `about:config`
. search for `xpinstall.signatures.required`
. Toggle it to `false`

* Exit Firefox

* *Find* the profile folder
+
....
$ cd ~/.mozilla/firefox/
$ find . -name \*dev-edition\*
./l062qyl2.dev-edition-default

$ cd l062qyl2.dev-edition-default/extensions/
....

* Create *a pointer file* here, it should look like this:
+
....
$ cat \{2df366ca-28d2-11e8-9c70-b7b0d99bd061\}
/home/peterm/work/qfeeds/firefox-qfeeds/
....
+
*Important* considerations
+
. Use full path to home folder, not `~`
+
. The name of the poiter file *matches* the field _id_ from _manifest.json_
+
. The trailing slash is important
+
. This *pointer file* is a left-over technique from the time of the
now *deprecated* XUL-format extensions. It is described here:
https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Setting_up_extension_development_environment[Setting
up extension development environment] (mozilla.org), see section
"Firefox extension proxy file"

* *Activate the extension* from page `about:addons`. Toggle the
  enable/disable switch-box button for extension QFeeds.

* Once *the setup of devel version is done* Firefox Developer Edition
  can be started conveniently with:
+
....
$ (cd ~/.local/bin/firefox; ./firefox&)
....

* To *reload the extension* after edits, Ctrl+R

* To *reload the extension* after edits of `manifest.json`, restart Firefox Developer
Edition

* To be able to navigate the *source files* while in the Debugger set
  the option "Enable browser and add-on debugging toolboxes" to
  ON. Restart the browser.

* Alternative way to see the sources in the debugger is via the page
  `about:debugging#/runtime/this-firefox`, button "Inspect" for QFeeds

* Go to `about:debugging` to inspect the UUID of the extension

== Debug functions ==

From the browser's console can be invoked a list of debug functions

=== Force fresh reload of remote feeds ===

* Delete local IndexedDB of subscribed feeds

* Reset cached version ID of the remote table

....
>> feeds_ns.app.m_feedsDir.m_feedsDB.feedUnsubscribeAll()
[Debug] Delete all subscriptions from IndexedDB...'
[Debug] Done, deleted 8 RSS subsciptions

>> feeds_ns.app.m_feedsDir.m_feedsDB.feedResetRTableConnection()
....

Close and re-open the extension. It should load all remote entries
into local IndexedDB

=== Add example entries ===

....
>> feeds_ns.app.m_feedsDir.m_feedsDB.feedAddByUrl1()
[Debug] Added https://...

>> feeds_ns.app.m_feedsDir.m_feedsDB.feedAddByUrl2()
[Debug] Added https://...
....
